insert or ignore into exams (id, slug, title, role) values
  ('nclex-rn', 'nclex-rn', 'NCLEX-RN', 'Registered nurse'),
  ('nclex-pn', 'nclex-pn', 'NCLEX-PN', 'Practical nurse'),
  ('ati-teas', 'ati-teas', 'ATI TEAS', 'Nursing entrance'),
  ('hesi-a2', 'hesi-a2', 'HESI A2', 'Health entrance'),
  ('comptia-security-plus', 'comptia-security-plus', 'CompTIA Security+', 'Cybersecurity'),
  ('comptia-a-plus', 'comptia-a-plus', 'CompTIA A+', 'IT support'),
  ('comptia-network-plus', 'comptia-network-plus', 'CompTIA Network+', 'Networking'),
  ('aws-cloud-practitioner', 'aws-cloud-practitioner', 'AWS Cloud Practitioner', 'Cloud fundamentals'),
  ('cisco-ccna', 'cisco-ccna', 'Cisco CCNA', 'Network associate'),
  ('cissp', 'cissp', 'CISSP', 'Security leadership'),
  ('cisa', 'cisa', 'CISA', 'IT audit'),
  ('pmp', 'pmp', 'PMP', 'Project manager'),
  ('capm', 'capm', 'CAPM', 'Associate project manager'),
  ('shrm-cp', 'shrm-cp', 'SHRM-CP', 'HR professional'),
  ('phr', 'phr', 'PHR', 'HR professional'),
  ('cpc', 'cpc', 'CPC', 'Medical coder'),
  ('ptce', 'ptce', 'PTCE', 'Pharmacy technician'),
  ('nha-ccma', 'nha-ccma', 'NHA CCMA', 'Clinical medical assistant'),
  ('nremt-emt', 'nremt-emt', 'NREMT EMT', 'Emergency medical technician'),
  ('nremt-paramedic', 'nremt-paramedic', 'NREMT Paramedic', 'Paramedic'),
  ('fnp', 'fnp', 'FNP', 'Family nurse practitioner'),
  ('cen', 'cen', 'CEN', 'Emergency nurse'),
  ('ccrn', 'ccrn', 'CCRN', 'Critical care nurse'),
  ('nasm-cpt', 'nasm-cpt', 'NASM CPT', 'Personal trainer'),
  ('nsca-cscs', 'nsca-cscs', 'NSCA CSCS', 'Strength and conditioning'),
  ('vtne', 'vtne', 'VTNE', 'Veterinary technician'),
  ('npte-pt', 'npte-pt', 'NPTE PT', 'Physical therapist'),
  ('nbcot-otr', 'nbcot-otr', 'NBCOT OTR', 'Occupational therapist'),
  ('leed-green-associate', 'leed-green-associate', 'LEED Green Associate', 'Sustainability'),
  ('apics-cpim', 'apics-cpim', 'APICS CPIM', 'Supply chain');
